description = "Ada Industrial Control Widgets Library"
name = "aicwl"
version = "3.24"
authors = ["Dmitry A. Kazakov <mailbox@dmitry-kazakov.de>"]
website = "http://www.dmitry-kazakov.de/ada/aicwl.htm"
licenses = ["GPL 2.0"]
maintainers = ["vinzent@heisenbug.eu"]
maintainers-logins = ["Jellix"]
project-files = ["sources/aicwl.gpr"]
tags = ["widgets", "gauge", "graphics", "ui", "gtk"]

[[depends-on]]
libgtkada = "^19"
