description = "Ada Industrial Control Widgets Library"
name = "aicwl"
version = "3.24.0"
authors = ["Dmitry A. Kazakov <mailbox@dmitry-kazakov.de>"]
website = "http://www.dmitry-kazakov.de/ada/aicwl.htm"
licenses = ["GMGPL 2.0"]
maintainers = ["vinzent@heisenbug.eu"]
maintainers-logins = ["Jellix"]
project-files = ["sources/aicwl.gpr"]
tags = ["widgets", "gauge", "graphics", "ui", "gtk"]

[gpr-externals]
Legacy                 = ["Ada95", "Ada2005", "Ada2012"]
Development            = ["Debug", "Release", "Profile"]
Target_OS              = ["Windows", "Windows_NT", "Linux", "UNIX", "OSX", "FreeBSD", "auto"]
Arch                   = ["x86_64", "i686", "armhf", "aarch64", "auto"]
Object_Dir_Scheme_Type = [".", "nested"]

[[depends-on]]
gtkada = ">=17"
libgio = "2.0"
